CC = gcc
CFLAGS = -Wall -Werror -pedantic

parse: parse.c

ioctl: ioctl.c

evtest: evtest.c

inotify: inotify.c

struct_init: struct_init.c

clean:
	rm *.o parse ioctl inotify struct_init 2> /dev/null
