CC = gcc
CFLAGS = -Wall -std=c99 -g

parse: parse.c

parse_v2: parse_v2.c

ioctl: ioctl.c

evtest: evtest.c

inotify: inotify.c

struct_init: struct_init.c

clean:
	rm -f *.o parse parse_v2 ioctl inotify struct_init
